name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "loft_orbital"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=.pylintrc"
          isort-options: "-w 120 --profile black"
          django: true

      - name: Run Tests
        run: |
          pip install pytest pytest-django
          python -m pytest loft_orbital
